### ISSUE TITLE
KA CHOW

### ISSUE THREAD

**Issue by webdev522** [velopert/velofolio#1]
Ka chow!

We will have another great project from Vel!!!
Thanks and hope this project goes well.
And happy new year!(I know it's too late, but I wanted to say it. I was too busy with my projects that have redux-pender in their package.json)
Remove this issue I only made to attract your eyes.(Sorry)

Regards,
webdev522.

**Comment by velopert** [comment]
Are you doing well Webdev?
I've never seen you on Live Coding season 3 !

By the way, I will do a live stream on 5.1 11PM (10PM for China), and share my experience on developing this project!
I am so sorry for not maintaining redux-pender :( 

Try using react-query for new features! It is awesome.
